package com.sm.spagent.model

enum class ImageType {
  OWNER,
  OWNER_NID_FRONT,
  OWNER_NID_BACK,
  OWNER_SIGNATURE,
  TRADE_LICENSE,
  SHOP_FRONT,
  NOMINEE,
  NOMINEE_NID_FRONT,
  NOMINEE_NID_BACK
}
